/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ViewKK;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author dhivazhr
 */
public class ProposalAnggaranKegiatan extends javax.swing.JPanel {

    /**
     * Creates new form ProposalAnggaranKegiatan
     */
    public ProposalAnggaranKegiatan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txFieldNamaKegiatan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnProfileKK = new javax.swing.JButton();
        btnNotif = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txFieldJenisKegiatan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbTanggalKegiatan = new javax.swing.JComboBox();
        cbTahunKegiatan = new javax.swing.JComboBox();
        cbBulanKegiatan = new javax.swing.JComboBox();
        txFieldDescKegiatan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txFieldAnggaranKegiatan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Proposal Anggaran Kegiatan");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Kegiatan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PERAK");

        btnHome.setText("jButton1");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnProfileKK.setIcon(new javax.swing.ImageIcon("C:\\Users\\8.1\\Downloads\\people.png")); // NOI18N
        btnProfileKK.setBorder(null);
        btnProfileKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileKKActionPerformed(evt);
            }
        });

        btnNotif.setText("jButton2");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jenis Kegiatan");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Kegiatan");

        cbTanggalKegiatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTahunKegiatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbBulanKegiatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txFieldDescKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldDescKegiatanActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Deskripsi Kegiatan");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Anggaran");

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 64, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProfileKK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                .addComponent(btnSelesai))
                            .addComponent(txFieldAnggaranKegiatan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFieldDescKegiatan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFieldNamaKegiatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txFieldJenisKegiatan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cbTanggalKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbBulanKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(cbTahunKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfileKK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnNotif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNamaKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txFieldJenisKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cbTanggalKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbTahunKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBulanKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txFieldDescKegiatan)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txFieldAnggaranKegiatan)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnBatal))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnProfileKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileKKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfileKKActionPerformed

    private void txFieldDescKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldDescKegiatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldDescKegiatanActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelesaiActionPerformed

    //GETTER BUTTON
    public JButton getBtnBatal() {
        return btnBatal;
    }

    public JButton getBtnHome() {
        return btnHome;
    }

    public JButton getBtnNotif() {
        return btnNotif;
    }

    public JButton getBtnProfileKK() {
        return btnProfileKK;
    }

    public JButton getBtnSelesai() {
        return btnSelesai;
    }

    //SETTER&GETTER TEXT FIELD
    public String getTxFieldAnggaranKegiatan() {
        return txFieldAnggaranKegiatan.getText();
    }

    public void setTxFieldAnggaranKegiatan(String AnggaranKegiatan) {
        txFieldAnggaranKegiatan.setText(AnggaranKegiatan);
    }

    public String getTxFieldDescKegiatan() {
        return txFieldDescKegiatan.getText();
    }

    public void setTxFieldDescKegiatan(String DescKegiatan) {
        txFieldDescKegiatan.setText(DescKegiatan);
    }

    public String getTxFieldJenisKegiatan() {
        return txFieldJenisKegiatan.getText();
    }

    public void setTxFieldJenisKegiatan(String JenisKegiatan) {
        txFieldJenisKegiatan.setText(JenisKegiatan);
    }

    public String getTxFieldNamaKegiatan() {
        return txFieldNamaKegiatan.getText();
    }

    public void setTxFieldNamaKegiatan(String NamaKegiatan) {
        txFieldNamaKegiatan.setText(NamaKegiatan);
    }

    //SETTER&GETTER COMBO BOX
    public String getCbBulanKegiatan() {
        return cbBulanKegiatan.getSelectedItem().toString();
    }

    public void setCbBulanKegiatan(String BulanKegiatan) {
        cbBulanKegiatan.addItem("Januari");
        cbBulanKegiatan.addItem("Februari");
        cbBulanKegiatan.addItem("Maret");
        cbBulanKegiatan.addItem("April");
        cbBulanKegiatan.addItem("Mei");
        cbBulanKegiatan.addItem("Juni");
        cbBulanKegiatan.addItem("Juli");
        cbBulanKegiatan.addItem("Agustus");
        cbBulanKegiatan.addItem("September");
        cbBulanKegiatan.addItem("Oktober");
        cbBulanKegiatan.addItem("November");
        cbBulanKegiatan.addItem("Desember");
    }

    public String getCbTahunKegiatan() {
        return cbTahunKegiatan.getSelectedItem().toString();
    }

    public void setCbTahunKegiatan(String TahunKegiatan) {
        cbTahunKegiatan.addItem("2015");
        cbTahunKegiatan.addItem("2016");
    }

    public String getCbTanggalKegiatan() {
        return cbTanggalKegiatan.getSelectedItem().toString();
    }

    public void setCbTanggalKegiatan(String TanggalKegiatan) {
        cbTanggalKegiatan.addItem("1");
        cbTanggalKegiatan.addItem("2");
        cbTanggalKegiatan.addItem("3");
        cbTanggalKegiatan.addItem("4");
        cbTanggalKegiatan.addItem("5");
        cbTanggalKegiatan.addItem("6");
        cbTanggalKegiatan.addItem("7");
        cbTanggalKegiatan.addItem("8");
        cbTanggalKegiatan.addItem("9");
        cbTanggalKegiatan.addItem("10");
        cbTanggalKegiatan.addItem("11");
        cbTanggalKegiatan.addItem("12");
        cbTanggalKegiatan.addItem("13");
        cbTanggalKegiatan.addItem("14");
        cbTanggalKegiatan.addItem("15");
        cbTanggalKegiatan.addItem("16");
        cbTanggalKegiatan.addItem("17");
        cbTanggalKegiatan.addItem("18");
        cbTanggalKegiatan.addItem("19");
        cbTanggalKegiatan.addItem("20");
        cbTanggalKegiatan.addItem("21");
        cbTanggalKegiatan.addItem("22");
        cbTanggalKegiatan.addItem("23");
        cbTanggalKegiatan.addItem("24");
        cbTanggalKegiatan.addItem("25");
        cbTanggalKegiatan.addItem("26");
        cbTanggalKegiatan.addItem("27");
        cbTanggalKegiatan.addItem("28");
        cbTanggalKegiatan.addItem("29");
        cbTanggalKegiatan.addItem("30");
        cbTanggalKegiatan.addItem("31");
    }
    
    public void addListener(ActionListener ae) {
        btnBatal.addActionListener(ae);
        btnHome.addActionListener(ae);
        btnNotif.addActionListener(ae);
        btnProfileKK.addActionListener(ae);
        btnSelesai.addActionListener(ae);
        cbBulanKegiatan.addActionListener(ae);
        cbTahunKegiatan.addActionListener(ae);
        cbTanggalKegiatan.addActionListener(ae);
        txFieldAnggaranKegiatan.addActionListener(ae);
        txFieldDescKegiatan.addActionListener(ae);
        txFieldJenisKegiatan.addActionListener(ae);
        txFieldNamaKegiatan.addActionListener(ae);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnNotif;
    private javax.swing.JButton btnProfileKK;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JComboBox cbBulanKegiatan;
    private javax.swing.JComboBox cbTahunKegiatan;
    private javax.swing.JComboBox cbTanggalKegiatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField txFieldAnggaranKegiatan;
    private javax.swing.JTextField txFieldDescKegiatan;
    private javax.swing.JTextField txFieldJenisKegiatan;
    private javax.swing.JTextField txFieldNamaKegiatan;
    // End of variables declaration//GEN-END:variables
}
